/**********************************************************************************************************************
 * \file gfx.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include <stdio.h>


/* PDL and board */
#include "cy_pdl.h"
#include "cybsp.h"

/* Graphics Driver */
#include "cygfx_driver_api.h"

/* Util library */
#include "cygfx_sysinit.h"
#include "cygfx_window.h"
#include "sm_util.h"
#include "ut_compatibility.h"
#include "ut_disp.h"
#include "ut_disp_panels.h"
#include "ut_memman.h"
#include "gfx.h"
/* This include contains all matrix related definitions */
#include "pe_matrix.h"

#include "res.h"
#include "time.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define DISPLAY_WIDTH           (800)
#define DISPLAY_HEIGHT          (480)

#define WINDOW_WIDTH            (600)
#define WINDOW_HEIGHT           (360)

#define TASK_INSTR_BUFFER_SIZE  (16 * 1024)

#define NUM_BARS        6     /* Configurable number of bars*/
#define NUM_PATTERNS    6     /* Configurable number of patterns*/
#define BAR_WIDTH       100
#define MAX_BAR_HEIGHT  300
#define BAR_SPACING     120
#define BAR_START_X     60
#define BAR_START_Y     150

/* Animation configuration */
#define UPDATE_SPEED    3     /* How fast bars change (pixels per frame) */
#define RANDOM_CHANCE   2     /*  1 in N chance to change direction each frame */
#define MIN_BAR_HEIGHT  20    /*  Minimum visible height */
#define ANIMATION_SPEED 1.5f  /*  Smoothing factor for height changes */


/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
typedef struct
{
    CYGFX_WINDOW            win;
    CYGFX_SURFACE           surfFramebuffer[2];
    CYGFX_SYNC_OBJECT_S     sync;
    CYGFX_U08               id;
} DoubleBufferedWindow;


/*  bar structure */
typedef struct {
    CYGFX_FLOAT currentHeight;       /* Current bar height in pixels */
    CYGFX_FLOAT targetHeight;        /* Target bar height in pixels */
    CYGFX_WINDOW window;             /* Window for this bar */
    CYGFX_SURFACE_OBJECT_S surface;  /* Solid color surface */
    CYGFX_U32 barIndex;              /* Bar index for positioning */
    CYGFX_S32 baseX;                 /* Base X position */
    CYGFX_S32 baseY;                 /* Base Y position (bottom of bar area) */
} DynamicBar;


/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
static CYGFX_DISP             disp;
static CYGFX_BE_CONTEXT       ctx;
static void*                  taskInstrBuffer;
static DoubleBufferedWindow   db;
static CYGFX_WINDOW           backgroundWindow = NULL;
static CYGFX_SURFACE_OBJECT_S backgroundSurface;
static DynamicBar             bars[NUM_BARS];
static const CYGFX_U08*       patterns[NUM_PATTERNS] = {pattern1, pattern2, pattern3, pattern4, pattern5,pattern6};
static CYGFX_U32              frameCount = 0;

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
static void         initVideoSSInterrupts(void);
static CYGFX_ERROR  initDriverAndDisplay(void);
static void         initSync(void);
static CYGFX_ERROR  initWindowsAndSurface(void);
static void         initRandom(void);
static CYGFX_ERROR  initDynamicBar(DynamicBar* bar, CYGFX_U32 index);
static CYGFX_S32    randomRange(CYGFX_S32 min, CYGFX_S32 max);
static CYGFX_ERROR  loadColorSurface(CYGFX_U08 index, CYGFX_SURFACE_OBJECT_S* surface);
static CYGFX_ERROR  loadBackground(void);
static CYGFX_ERROR  updateBarHeight(DynamicBar* bar);
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/**********************************************************************************************************************
 * Function Name: initGfx
 * Summary:
 *  Initializes all required subsystems
 * Parameters:
 *  none
 * Return:
 *  CYGFX_ERROR returns error status
 **********************************************************************************************************************
 */
CYGFX_ERROR initGfx(void)
{
	CYGFX_ERROR ret = CYGFX_OK;
    initVideoSSInterrupts();
    UTIL_SUCCESS(ret, initDriverAndDisplay());
    initSync();
    UTIL_SUCCESS(ret, initWindowsAndSurface());
    initRandom();

    return ret;
}


/**********************************************************************************************************************
 * Function Name: deInitGfx
 * Summary:
 *  Deinitializes subsystems and frees memory.
 * Parameters:
 *  none
 * Return:
 *  none
 **********************************************************************************************************************
 */
void deInitGfx(void)
{

    CYGFX_U32 i;

    printf("Cleaning up dynamic bar graph...\n");

    /* Cleanup bar resources */
    for (i = 0; i < NUM_BARS; i++) {
        if (bars[i].window) {
            CyGfx_WinDestroy(bars[i].window);
        }
        utSurfDeleteBuffer(&bars[i].surface);
    }
    
    /* Cleanup background */
    if (backgroundWindow) {
        CyGfx_WinDestroy(backgroundWindow);
    }
    utSurfDeleteBuffer(&backgroundSurface);

    /* Close display */
    if (disp) {
        CyGfx_DispCloseDisplay(disp);
    }

    /* Task Instruction buffers */
    utVideoFree(taskInstrBuffer);
    
    /* Contexts */
    utPeDeleteContext(ctx);
    
    /* Display */
    CyGfx_DispCloseDisplay(disp);
    
    /* Driver */
    CyGfx_SysDeInitializeDriver();

    printf("Dynamic bar graph cleanup complete.\n");
}


/**********************************************************************************************************************
 * Function Name: initVideoSSInterrupts
 * Summary:
 *  Initialises VIDEOSS Interrupts
 * Parameters:
 *  none
 * Return:
 *  none
 **********************************************************************************************************************
 */
static void initVideoSSInterrupts(void)
{
    /* VideoSS interrupts configurations */
    const cy_stc_sysint_t IRQ_VIDEOSS_GFX2D_CFG =
    {
        .intrSrc  = ((NvicMux3_IRQn << CY_SYSINT_INTRSRC_MUXIRQ_SHIFT) | videoss_0_interrupt_gfx2d_IRQn),
        .intrPriority = 3UL
    };

    const cy_stc_sysint_t IRQ_VIDEOSS_VIDEOIO0_CFG =
    {
        .intrSrc  = ((NvicMux3_IRQn << CY_SYSINT_INTRSRC_MUXIRQ_SHIFT) | videoss_0_interrupt_videoio0_IRQn),
        .intrPriority = 3UL
    };
    
    const cy_stc_sysint_t IRQ_VIDEOSS_VIDEOIO1_CFG =
    {
        .intrSrc  = ((NvicMux3_IRQn << CY_SYSINT_INTRSRC_MUXIRQ_SHIFT) | videoss_0_interrupt_videoio1_IRQn),
        .intrPriority = 3UL
    };

    /* Initialize VideoSS interrupts */
    CY_ASSERT(Cy_SysInt_Init(&IRQ_VIDEOSS_GFX2D_CFG, CyGfx_kInterruptHandlerGfx2d) == CY_SYSINT_SUCCESS);
    CY_ASSERT(Cy_SysInt_Init(&IRQ_VIDEOSS_VIDEOIO0_CFG, CyGfx_kInterruptHandlerVideoio0) == CY_SYSINT_SUCCESS);
    CY_ASSERT(Cy_SysInt_Init(&IRQ_VIDEOSS_VIDEOIO1_CFG, CyGfx_kInterruptHandlerVideoio1) == CY_SYSINT_SUCCESS);
    
    /* Enable the corresponding NVIC interrupt */
    NVIC_EnableIRQ(NvicMux3_IRQn);
}

/**********************************************************************************************************************
 * Function Name: initDriverAndDisplay
 * Summary:
 *  Initializes the driver and a 800x480 display shown via FX3. Required timings are
 *  properly setup by adjusting PLLs. Driver and display need same timing information,
 *  thus both done in the same function.
 * Parameters:
 *  none
 * Return:
 *  CYGFX_ERROR error status
 **********************************************************************************************************************
 */
static CYGFX_ERROR initDriverAndDisplay(void)
{
    CYGFX_ERROR ret = CYGFX_OK;
    
    CYGFX_SYSINIT_INFO_S initInfo = CYGFX_SYS_INIT_INITIALIZER;
    CYGFX_DISP_PROPERTIES_S dispProps = CYGFX_DISP_PROPERTIES_INITIALIZER;
    CYGFX_U08 clockDivider;
    
    /* Use timing properties located in util library for 800x480 display */
    dispProps = s_panel_XXX_800_480;
    dispProps.pTconProps = NULL;
    dispProps.countTconProps = 0;
    dispProps.outputController = CYGFX_DISP_CONTROLLER_1;
    
    /* Calculate PLL based on pixel clock and enable. PLL_1 is used for FX3 output */
    UTIL_SUCCESS(ret, utDispGetPll(dispProps.timing.pixelClock, dispProps.displayMode, &clockDivider, &initInfo.PllDsp1));
    UTIL_SUCCESS(ret, utDispEnablePll(initInfo.PllDsp1, dispProps.outputController));
    
    /* Init driver and reset memory manager */
    UTIL_SUCCESS(ret, CyGfx_SysInitializeDriver(&initInfo));
    UTIL_SUCCESS(ret, utMmanReset());
    
    /* Enable display */
    UTIL_SUCCESS(ret, CyGfx_DispOpenDisplay(&dispProps, &disp, NULL));
    
    return ret;

}


/**********************************************************************************************************************
 * Function Name: initSync
 * Summary:
 *  Initializes all used sync objects.
 * Parameters:
 *  none
 * Return:
 *  none
 **********************************************************************************************************************
 */
static void initSync(void)
{
    CyGfx_SyncReset(&db.sync);
}


/**********************************************************************************************************************
 * Function Name: initWindowsAndSurface
 * Summary:
 *  Initializes all windows with respective properties.
 * Parameters:
 *  none
 * Return:
 *  none
 **********************************************************************************************************************
 */
static CYGFX_ERROR initWindowsAndSurface(void)
{

	CYGFX_ERROR ret = CYGFX_OK;

    CYGFX_DISP_WINDOW_PROPERTIES_S winProps = CYGFX_DISP_WINDOW_PROPERTIES_INITIALIZER;
    
    /* Create background surface */
	ret = CyGfx_SmResetSurfaceObject(&backgroundSurface);
	if (ret != CYGFX_OK) return ret;

	ret = loadBackground();
	if (ret != CYGFX_OK) return ret;

    /* Create background window (Layer 0) */
    winProps.topLeftX = 0;
    winProps.topLeftY = 0;
    winProps.width = DISPLAY_WIDTH;
    winProps.height = DISPLAY_HEIGHT;
    winProps.layerId = CYGFX_DISP_LAYER_0;
    winProps.features = 0;

    ret = CyGfx_DispWinCreate(disp, &winProps, &backgroundWindow);
    if (ret != CYGFX_OK) return ret;

    ret = CyGfx_WinSetSurface(backgroundWindow, CYGFX_DISP_BUFF_TARGET_COLOR_BUFF, &backgroundSurface);
    if (ret != CYGFX_OK) return ret;

    ret = CyGfx_WinCommit(backgroundWindow);
    if (ret != CYGFX_OK) return ret;

    /* Initialize all dynamic bars */
    for (CYGFX_U32 i = 0; i < NUM_BARS; i++) {
        ret = initDynamicBar(&bars[i], i);
        if (ret != CYGFX_OK) {
            printf("ERROR: Failed to initialize dynamic bar %u (0x%08x)\n", (unsigned int)i, (unsigned int)ret);
            return ret;
        }
    }

    return ret;
}




/**********************************************************************************************************************
 * Function Name: initRandom
 * Summary:
 *  Initializes initialise random number
 * Parameters:
 *  none
 * Return:
 *  none
 **********************************************************************************************************************
 */
static void initRandom(void)
{
    srand((unsigned int)time(NULL));
}

/**********************************************************************************************************************
 * Function Name: randomRange
 * Summary:
 *  returns a random number between min and max
 * Parameters:
 * min    minimum value in range
 * max    maximum value in range
 * Return:
 *  CYGFX_S32     random value in range
 **********************************************************************************************************************
 */
static CYGFX_S32 randomRange(CYGFX_S32 min, CYGFX_S32 max)
{
    return min + (rand() % (max - min + 1));
}

/**********************************************************************************************************************
 * Function Name: loadColorSurface
 * Summary:
 *  loaded image into the surface
 * Parameters:
 * index    surface index
 * surface   surface pointer
 * Return:
 *  CYGFX_ERROR     returns status
 **********************************************************************************************************************
 */
static CYGFX_ERROR loadColorSurface(CYGFX_U08 index, CYGFX_SURFACE_OBJECT_S* surface)
{
    CYGFX_ERROR ret;

    ret = CyGfx_SmResetSurfaceObject(surface);
    if (ret != CYGFX_OK) return ret;

    ret = utSurfLoadBitmap(surface, patterns[index], CYGFX_FALSE);
    if (ret != CYGFX_OK) return ret;

    return CYGFX_OK;
}

/**********************************************************************************************************************
 * Function Name: loadBackground
 * Summary:
 *  loaded image into background
 * Parameters:
 * Return:
 *  CYGFX_ERROR     returns status
 **********************************************************************************************************************
 */
static CYGFX_ERROR loadBackground(void)
{
    CYGFX_ERROR ret;

    /* Get surface buffer pointer */
    ret = utSurfLoadBitmap(&backgroundSurface, background, CYGFX_FALSE);
    if (ret != CYGFX_OK) return ret;

    return CYGFX_OK;
}

/**********************************************************************************************************************
 * Function Name: initDynamicBar
 * Summary:
 *  initialises Bar element with parameters and also maps each to the sub window
 * Parameters:
 * bar      bar element that needs to be initialsed
 * index	index of bar
 * Return:
 *  CYGFX_ERROR     returns status
 **********************************************************************************************************************
 */
static CYGFX_ERROR initDynamicBar(DynamicBar* bar, CYGFX_U32 index)
{
    CYGFX_ERROR ret = CYGFX_OK;
    CYGFX_DISP_WINDOW_PROPERTIES_S winProps = CYGFX_DISP_WINDOW_PROPERTIES_INITIALIZER;

    /* Initialize bar data */
    bar->currentHeight = (CYGFX_FLOAT)MIN_BAR_HEIGHT;
    bar->targetHeight = (CYGFX_FLOAT)randomRange(MIN_BAR_HEIGHT, MAX_BAR_HEIGHT);

    bar->barIndex = index;
    bar->baseX = BAR_START_X + (index * BAR_SPACING);
    bar->baseY = BAR_START_Y + MAX_BAR_HEIGHT; /* Bottom of the bar area */

    /* Load the surface */
    ret = loadColorSurface(bar->barIndex, &bar->surface);
    if (ret != CYGFX_OK) return ret;

    /* Create window for the bar */
    winProps.topLeftX = bar->baseX;
    winProps.topLeftY = bar->baseY - (CYGFX_S32)bar->currentHeight; /* Position from bottom */
    winProps.width = BAR_WIDTH;
    winProps.height = (CYGFX_U32)bar->currentHeight;
    winProps.layerId = CYGFX_DISP_LAYER_1;
    winProps.features = CYGFX_DISP_FEATURE_MULTI_LAYER;

    ret = CyGfx_DispWinCreate(disp, &winProps, &bar->window);
    if (ret != CYGFX_OK) return ret;

    /* Assign surface to window */
    ret = CyGfx_WinSetSurface(bar->window, CYGFX_DISP_BUFF_TARGET_COLOR_BUFF, &bar->surface);
    if (ret != CYGFX_OK) return ret;

    /* Set blend mode */
    ret = CyGfx_WinSetBlendMode(bar->window, CYGFX_WIN_BLEND_SOURCE_ALPHA);
    if (ret != CYGFX_OK) return ret;

    /* Commit initial window settings */
    ret = CyGfx_WinCommit(bar->window);
    if (ret != CYGFX_OK) return ret;

    return CYGFX_OK;
}

/**********************************************************************************************************************
 * Function Name: updateBarHeight
 * Summary:
 *  updates height of the attached window to the bar
 * Parameters:
 * bar      bar element that needs to be updated
 * Return:
 *  CYGFX_ERROR     returns status
 **********************************************************************************************************************
 */
static CYGFX_ERROR updateBarHeight(DynamicBar* bar)
{
    CYGFX_ERROR ret = CYGFX_OK;
    CYGFX_U32 newHeight;
    CYGFX_S32 newY;

    /* Ensure minimum height */
    if (bar->currentHeight < MIN_BAR_HEIGHT) {
        bar->currentHeight = MIN_BAR_HEIGHT;
    }
    if (bar->currentHeight > MAX_BAR_HEIGHT) {
        bar->currentHeight = MAX_BAR_HEIGHT;
    }

    newHeight = (CYGFX_U32)bar->currentHeight;
    newY = bar->baseY - (CYGFX_S32)newHeight; /* Position from bottom up */

    /* Update window height */
    ret = CyGfx_WinSetAttribute(bar->window, CYGFX_WIN_ATTR_HEIGHT, newHeight);
    if (ret != CYGFX_OK) return ret;

    /* Update window Y position to grow from bottom */
    ret = CyGfx_WinSetAttribute(bar->window, CYGFX_WIN_ATTR_TOPLEFT_Y, newY);
    if (ret != CYGFX_OK) return ret;

    /* Commit changes */
    ret = CyGfx_WinCommit(bar->window);
    if (ret != CYGFX_OK) return ret;

    return CYGFX_OK;
}

/**********************************************************************************************************************
 * Function Name: updateBarLogic
 * Summary:
 *  height update logic witht the random number is done here.
 * Parameters:
 * bar      bar element that needs to be updated
 * Return:
 *  CYGFX_ERROR     returns status
 **********************************************************************************************************************
 */
static CYGFX_ERROR updateBarLogic(DynamicBar* bar)
{
    CYGFX_ERROR ret  = CYGFX_OK;
	CYGFX_BOOL heightChanged = CYGFX_FALSE;

    /* Smooth movement towards target height */
    CYGFX_FLOAT heightDiff = bar->targetHeight - bar->currentHeight;
    if (fabs(heightDiff) > 1.0f) {
        bar->currentHeight += heightDiff * ANIMATION_SPEED * 0.1f; /* Smooth interpolation */
        heightChanged = CYGFX_TRUE;
    } else if (fabs(heightDiff) > 0.1f) {
        bar->currentHeight = bar->targetHeight; /* Snap to target when close */
        heightChanged = CYGFX_TRUE;
    }

    /* Randomly change target height */
    if (randomRange(1, 100) <= RANDOM_CHANCE) {
        bar->targetHeight = (CYGFX_FLOAT)randomRange(MIN_BAR_HEIGHT, MAX_BAR_HEIGHT);
    }

    /* Update window height if changed */
    if (heightChanged) {
        ret = updateBarHeight(bar);
    }

    return ret;
}


/**********************************************************************************************************************
 * Function Name: gfxLoop
 * Summary:
 *  main cyclic function, needs to be called continuously, updated every frame
 * Parameters:
 * bar      bar element that needs to be updated
 * Return:
 *  CYGFX_ERROR     returns status
 **********************************************************************************************************************
 */
CYGFX_ERROR gfxLoop(void)
{
    CYGFX_U32 i;
    CYGFX_ERROR ret = CYGFX_OK;

    /* Update all bars */
    for (i = 0; i < NUM_BARS; i++) {
        ret = updateBarLogic(&bars[i]);
    }

    frameCount++;

    return ret;
}


