################################################################################
# \file bsp.mk
#
# \brief
# Define the KIT_T2G_C-2D-4M_LITE target.
#
################################################################################
# \copyright
# Copyright 2025 Cypress Semiconductor Corporation (an Infineon company) or
# an affiliate of Cypress Semiconductor Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

ifeq ($(WHICHFILE),true)
$(info Processing $(lastword $(MAKEFILE_LIST)))
endif

# Any additional components to apply when using this board.
# Use a default CM0+ image (CM0P_SLEEP). This can be swapped for a
# different pre-built image or removed if custom built project.
# Seems like this kit should have multi-core applications only
BSP_COMPONENTS:=CM0P_SLEEP

# Any additional defines to apply when using this board.
BSP_DEFINES:=CY_DISABLE_XMC7000_DATA_CACHE
BSP_DEFINES:=BACKGROUND_IMG_4M

# Path to the flash loaders to patch for this board
# CY_QSPI_FLM_DIR=$(MTB_TOOLS__TARGET_DIR)/config/FlashLoaders/

# Path to the patched flash loaders for this board
# CY_QSPI_FLM_DIR_OUTPUT=$(MTB_TOOLS__TARGET_DIR)/config/GeneratedSource/

# Middleware graphics support for CYT4DN devices requires single-precision
# hardware floating point.  Changing to soft floating point or the precision 
# will cause compatibility issues with graphics.
VFP_SELECT=hardfp
VFP_SELECT_PRECISION=singlefp

ifeq ($(TOOLCHAIN),GCC_ARM)
	BSP_LINKER_SCRIPT_EXT:=ld
else ifeq ($(TOOLCHAIN),ARM)
	BSP_LINKER_SCRIPT_EXT:=sct
else ifeq ($(TOOLCHAIN),IAR)
	BSP_LINKER_SCRIPT_EXT:=icf
endif
MTB_BSP__LINKER_SCRIPT=$(MTB_TOOLS__TARGET_DIR)/COMPONENT_$(MTB_RECIPE__CORE)/TOOLCHAIN_$(TOOLCHAIN)/linker.$(BSP_LINKER_SCRIPT_EXT)
$(info "Using linker $(MTB_BSP__LINKER_SCRIPT)")
################################################################################
# ALL ITEMS BELOW THIS POINT ARE AUTO GENERATED BY THE BSP ASSISTANT TOOL.
# DO NOT MODIFY DIRECTLY. CHANGES SHOULD BE MADE THROUGH THE BSP ASSISTANT.
################################################################################

# Board device selection. MPN_LIST tracks what was selected in the BSP Assistant
# All other variables are derived by BSP Assistant based on the MPN_LIST.
MPN_LIST:=CYT3DLBBHS
DEVICE:=CYT3DLBBHS
DEVICE_COMPONENTS:=CAT1 CAT1C TVIIC2D4M
DEVICE_CYT3DLBBHS_CORES:=CORE_NAME_CM0P_0 CORE_NAME_CM7_0
DEVICE_CYT3DLBBHS_DIE:=TVIIC2D4M
DEVICE_CYT3DLBBHS_FEATURES:=CM7_0_FPU_PRESENT
DEVICE_CYT3DLBBHS_FLASH_KB:=4160
DEVICE_CYT3DLBBHS_IPBLOCKS:=M7CPUSS M7CPUSS_V1 MXAXIDMAC MXAXIDMAC_V1 MXCXPI MXCXPI_V1 MXDFT_VER2 MXDFT_VER2_V2 MXEFUSE_VER2 MXEFUSE_VER2_V2 MXETH MXETH_V2 MXEVTGEN MXEVTGEN_V1 MXLIN MXLIN_V1 MXMIXER_S40E MXMIXER_S40E_V1 MXPERI_VER3 MXPERI_VER3_V3 MXPWM_S40E MXPWM_S40E_V1 MXS40EAUDIODAC MXS40EAUDIODAC_V1 MXS40EPASS MXS40EPASS_V1 MXS40IOSS MXS40IOSS_V5 MXS40SRSS_VER3 MXS40SRSS_VER3_V3 MXSCB_VER2_S40E MXSCB_VER2_S40E_V2 MXSG_S40E MXSG_S40E_V1 MXSMIF MXSMIF_V3 MXTCPWM_VER2 MXTCPWM_VER2_V2 MXTDM MXTDM_V1 MXTTCANFD_S40E MXTTCANFD_S40E_V1 MXVIDEOSS MXVIDEOSS_V1
DEVICE_CYT3DLBBHS_SRAM_KB:=384
DEVICE_LIST:=CYT3DLBBHS
DEVICE_TOOL_IDS:=bsp-assistant device-configurator dfuh-tool library-manager project-creator qspi-configurator smartio-configurator
RECIPE_DIR:=$(SEARCH_recipe-make-cat1c)
